version: "3.9"

services:
  database:
    image: postgres
    env_file:
      - .env
    volumes:
      - ./private/docker/volumes/postgres:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/src
    ports:
      - "3000:3000"